# Generated by Django 4.2.23 on 2025-09-16 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_webhooksubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this consumer', max_length=100)),
                ('consumer_type', models.CharField(choices=[('mobile', 'Mobile App'), ('script', 'Script/CLI'), ('service', 'External Service'), ('webhook', 'Webhook Consumer')], default='mobile', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional consumer metadata (device info, etc.)')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('room', 'Room-based notifications'), ('provider', 'Provider-based notifications'), ('department', 'Department-based notifications'), ('user_role', 'User role-based notifications'), ('all', 'All notifications')], max_length=20)),
                ('tag_value', models.CharField(help_text='Value to match (room name, provider ID, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.consumer')),
            ],
            options={
                'ordering': ['tag_type', 'tag_value'],
                'unique_together': {('consumer', 'tag_type', 'tag_value')},
            },
        ),
        migrations.CreateModel(
            name='ConsumerNotificationPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_notifications', to='core.consumer')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_for_consumers', to='core.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('consumer', 'notification')},
            },
        ),
        migrations.CreateModel(
            name='ConsumerNotificationAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='core.consumer')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_acknowledgments', to='core.notification')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('consumer', 'notification')},
            },
        ),
    ]
