# Generated by Django 4.2.23 on 2025-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumer_consumersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumernotificationpending',
            name='matched_tags',
            field=models.JSONField(default=dict, help_text='Which tags caused the match'),
        ),
    ]
