# Generated by Django 4.2.23 on 2025-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consumernotificationpending_matched_tags'),
    ]

    operations = [
        # Add indexes for better query performance
        
        # Consumer indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumer_status_idx ON core_consumer(status);",
            reverse_sql="DROP INDEX IF EXISTS core_consumer_status_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumer_last_seen_idx ON core_consumer(last_seen_at);",
            reverse_sql="DROP INDEX IF EXISTS core_consumer_last_seen_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumer_type_status_idx ON core_consumer(consumer_type, status);",
            reverse_sql="DROP INDEX IF EXISTS core_consumer_type_status_idx;"
        ),
        
        # ConsumerSubscription indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumersubscription_tag_type_idx ON core_consumersubscription(tag_type);",
            reverse_sql="DROP INDEX IF EXISTS core_consumersubscription_tag_type_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumersubscription_tag_value_idx ON core_consumersubscription(tag_value);",
            reverse_sql="DROP INDEX IF EXISTS core_consumersubscription_tag_value_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumersubscription_tag_type_value_idx ON core_consumersubscription(tag_type, tag_value);",
            reverse_sql="DROP INDEX IF EXISTS core_consumersubscription_tag_type_value_idx;"
        ),
        
        # ConsumerNotificationAck indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumernotificationack_acked_at_idx ON core_consumernotificationack(acknowledged_at);",
            reverse_sql="DROP INDEX IF EXISTS core_consumernotificationack_acked_at_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumernotificationack_consumer_acked_idx ON core_consumernotificationack(consumer_id, acknowledged_at);",
            reverse_sql="DROP INDEX IF EXISTS core_consumernotificationack_consumer_acked_idx;"
        ),
        
        # ConsumerNotificationPending indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumernotificationpending_created_at_idx ON core_consumernotificationpending(created_at);",
            reverse_sql="DROP INDEX IF EXISTS core_consumernotificationpending_created_at_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_consumernotificationpending_consumer_created_idx ON core_consumernotificationpending(consumer_id, created_at);",
            reverse_sql="DROP INDEX IF EXISTS core_consumernotificationpending_consumer_created_idx;"
        ),
        
        # Notification indexes (for timestamp-based queries)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_notification_timestamp_idx ON core_notification(timestamp);",
            reverse_sql="DROP INDEX IF EXISTS core_notification_timestamp_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS core_notification_room_timestamp_idx ON core_notification(room_id, timestamp);",
            reverse_sql="DROP INDEX IF EXISTS core_notification_room_timestamp_idx;"
        ),
    ]
