# Generated by Django 4.2.23 on 2025-09-28 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250916_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObserverSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this observer', max_length=100)),
                ('observer_type', models.CharField(choices=[('mobile_app', 'Mobile App'), ('webhook', 'Webhook'), ('external_service', 'External Service'), ('script', 'Script/CLI')], default='mobile_app', max_length=20)),
                ('callback_url', models.URLField(help_text='URL to POST notifications to')),
                ('callback_method', models.CharField(default='POST', help_text='HTTP method for callbacks', max_length=10)),
                ('callback_headers', models.JSONField(blank=True, default=dict, help_text='Additional headers for callback requests')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0, help_text='Consecutive failures')),
                ('max_failures', models.IntegerField(default=5, help_text='Max failures before marking as failed')),
                ('timeout_seconds', models.IntegerField(default=10, help_text='Request timeout in seconds')),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retries on failure')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Observer metadata (device_id, user_id, etc.)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_subscriptions', to='core.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', 'status'], name='core_observ_room_id_e51800_idx'), models.Index(fields=['status', 'last_notified_at'], name='core_observ_status_16cb9c_idx')],
            },
        ),
    ]
